./gradlew generateVersionSVG clean assemble\
 e:publishReleasePublicationToSonatypeRepository\
 ae:publishReleasePublicationToSonatypeRepository\
 rxe:publishReleasePublicationToSonatypeRepository\
 util:publishReleasePublicationToSonatypeRepository\
 coroutines:publishReleasePublicationToSonatypeRepository