./gradlew generateVersionSVG generateReadme clean assemble\
 pure:publishReleasePublicationToSonatypeRepository\
 android:publishReleasePublicationToSonatypeRepository\
 rxe:publishReleasePublicationToSonatypeRepository\
 util:publishReleasePublicationToSonatypeRepository\
 coroutines:publishReleasePublicationToSonatypeRepository